"use server";

import { HfInference } from "@huggingface/inference";

// Text models confirmed working on HF router (Feb 2026)
// Mistral-7B-Instruct-v0.3 and Llama-3.2-8B are BROKEN (410 / "not a chat model")
const REPORT_MODELS = [
  "meta-llama/Llama-3.1-8B-Instruct",     // Fast, high quality
  "Qwen/Qwen2.5-72B-Instruct",            // Best quality fallback
  "mistralai/Mistral-7B-Instruct-v0.2",   // Lightweight fallback
];

export interface ReportParams {
  notes: string;
  imageDescriptions: string[];
  details: {
    inspectorName: string;
    companyName: string;
    companyAddress: string;
    clientName: string;
    propertyAddress: string;
    date: string;
  };
}

export async function generateReport({ notes, imageDescriptions, details }: ReportParams) {
  const token = process.env.HF_ACCESS_TOKEN;

  if (!token || token === "hf_placeholder") {
    return {
      success: false,
      error: "AI service not configured. Set HF_ACCESS_TOKEN in environment.",
    };
  }

  const imageSection =
    imageDescriptions.length > 0
      ? imageDescriptions.map((d, i) => `  Photo ${i + 1}: ${d}`).join("\n")
      : "  No photos uploaded.";

  const notesSection = notes.trim() || "No voice notes recorded.";

  const systemPrompt = `You are a licensed home inspector writing official inspection reports. Write in professional, objective, third-person language. Use Markdown formatting. Follow the structure exactly.`;

  const userPrompt = `Write a professional property inspection report using ONLY the information provided below. Do not invent findings not supported by the data.

## INSPECTION INFORMATION
- **Inspector:** ${details.inspectorName || "Not provided"}
- **Company:** ${details.companyName || "Not provided"} | ${details.companyAddress || ""}
- **Client:** ${details.clientName || "Not provided"}
- **Property:** ${details.propertyAddress || "Not provided"}
- **Date:** ${details.date || new Date().toLocaleDateString()}

## RAW FIELD DATA

### Voice Notes (verbatim):
${notesSection}

### Photo Analysis Results:
${imageSection}

---

## REPORT FORMAT REQUIREMENTS

Generate the report with these exact sections:

# PROPERTY INSPECTION REPORT

## Executive Summary
(2-3 sentences summarizing overall condition and key findings)

## Findings by System

For each finding observed in the data, use this structure:
**[System/Area]**
- **Observation:** What was seen
- **Condition:** Good / Fair / Poor / Critical
- **Recommendation:** Specific action required (if any)

## Priority Action Items
(Bulleted list of the most urgent items requiring immediate attention)

## Inspector Notes
(Any additional professional notes or disclaimers)

---
*Report generated by FieldScribe AI. This report documents conditions at time of inspection and does not constitute a warranty.*`;

  const hf = new HfInference(token);

  for (const model of REPORT_MODELS) {
    try {
      console.log(`[FieldScribe] Report generation → ${model}`);

      const response = await hf.chatCompletion({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        max_tokens: 2000,
        temperature: 0.2,
      });

      const report = response.choices?.[0]?.message?.content;

      if (typeof report === "string" && report.trim().length > 100) {
        console.log(`[FieldScribe] ✓ Report generated → ${model}`);
        return { success: true, report: report.trim() };
      }
    } catch (err) {
      console.warn(`[FieldScribe] Report gen failed (${model}):`, err instanceof Error ? err.message : err);
    }
  }

  return {
    success: false,
    error: "Report generation failed. AI service is busy — please try again in a moment.",
  };
}
