"use client";

import { useState } from "react";
import {
  Loader2,
  FileText,
  Download,
  Wand2,
  FileType,
  AlertCircle,
  Copy,
  CheckCheck,
} from "lucide-react";
import { generateReport } from "../actions/generate-report";
import { InspectionDetailsData } from "./InspectionDetails";
import { jsPDF } from "jspdf";

interface Props {
  notes: string[];
  imageAnalyses: string[];
  details: InspectionDetailsData;
}

export function ReportGenerator({ notes, imageAnalyses, details }: Props) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [report, setReport] = useState<string>("");
  const [errorMsg, setErrorMsg] = useState<string>("");
  const [copied, setCopied] = useState(false);

  const hasData = notes.length > 0 || imageAnalyses.length > 0;
  const hasDetails = !!(details.inspectorName || details.propertyAddress);

  const handleGenerate = async () => {
    if (!hasDetails) {
      setErrorMsg(
        "Please fill in at least the Inspector Name and Property Address before generating."
      );
      return;
    }
    if (!hasData) {
      setErrorMsg(
        "Please add at least one photo or voice note before generating."
      );
      return;
    }

    setIsGenerating(true);
    setErrorMsg("");

    const res = await generateReport({
      notes: notes.join("\n"),
      imageDescriptions: imageAnalyses,
      details,
    });

    if (res.success && res.report) {
      setReport(res.report);
    } else {
      setErrorMsg(
        res.error || "Report generation failed. Please try again."
      );
    }
    setIsGenerating(false);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadText = () => {
    const slug = (details.propertyAddress || "inspection")
      .replace(/[^a-z0-9]/gi, "-")
      .toLowerCase();
    const el = document.createElement("a");
    el.href = URL.createObjectURL(new Blob([report], { type: "text/plain" }));
    el.download = `FieldScribe-Report-${slug}.txt`;
    el.click();
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentW = pageW - margin * 2;
    let y = margin;

    const newPage = () => {
      doc.addPage();
      y = margin;
      // Page footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Generated by FieldScribe · ${details.date}`,
        margin,
        pageH - 10
      );
      doc.setTextColor(30);
    };

    const checkNewPage = (lineH: number) => {
      if (y + lineH > pageH - 20) newPage();
    };

    // ── Header Bar ──
    doc.setFillColor(79, 70, 229); // indigo-600
    doc.rect(0, 0, pageW, 38, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("PROPERTY INSPECTION REPORT", margin, 18);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by FieldScribe AI", margin, 27);
    doc.text(`Date: ${details.date}`, pageW - margin, 27, { align: "right" });
    y = 50;

    // ── Info Box ──
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, y, contentW, 34, 2, 2, "FD");
    doc.setTextColor(30);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("INSPECTOR", margin + 5, y + 8);
    doc.setFont("helvetica", "normal");
    doc.text(details.inspectorName || "—", margin + 5, y + 15);
    doc.text(details.companyName || "", margin + 5, y + 21);
    doc.text(details.companyAddress || "", margin + 5, y + 27);

    const midX = pageW / 2 + 5;
    doc.setFont("helvetica", "bold");
    doc.text("PROPERTY / CLIENT", midX, y + 8);
    doc.setFont("helvetica", "normal");
    doc.text(details.propertyAddress || "—", midX, y + 15);
    doc.text(`Client: ${details.clientName || "—"}`, midX, y + 21);
    y += 44;

    // ── Report Body ──
    const lines = report.split("\n");

    for (const rawLine of lines) {
      const line = rawLine.trimEnd();

      // H1
      if (line.startsWith("# ")) {
        checkNewPage(12);
        doc.setFontSize(15);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30);
        doc.text(line.replace(/^# /, ""), margin, y);
        y += 10;
        continue;
      }

      // H2
      if (line.startsWith("## ")) {
        checkNewPage(10);
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(79, 70, 229);
        doc.text(line.replace(/^## /, ""), margin, y);
        y += 8;
        // Underline
        doc.setDrawColor(199, 210, 254);
        doc.line(margin, y, margin + contentW, y);
        y += 4;
        continue;
      }

      // H3
      if (line.startsWith("### ")) {
        checkNewPage(8);
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(51, 65, 85);
        doc.text(line.replace(/^### /, ""), margin, y);
        y += 7;
        continue;
      }

      // Horizontal rule
      if (/^---+$/.test(line.trim())) {
        checkNewPage(6);
        doc.setDrawColor(226, 232, 240);
        doc.line(margin, y, margin + contentW, y);
        y += 5;
        continue;
      }

      // Blank line
      if (line.trim() === "") {
        y += 3;
        continue;
      }

      // Normal text (strip bold markers **)
      const cleanLine = line.replace(/\*\*([^*]+)\*\*/g, "$1").replace(/^\s*[-•*]\s*/, "• ");
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 65, 85);

      const wrapped = doc.splitTextToSize(cleanLine, contentW - 2);
      for (const wl of wrapped) {
        checkNewPage(6);
        const indent = wl.startsWith("• ") ? margin + 3 : margin;
        doc.text(wl, indent, y);
        y += 5.5;
      }
    }

    // Footer on last page
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by FieldScribe AI · ${details.date}`,
      margin,
      pageH - 10
    );

    const slug = (details.propertyAddress || "inspection")
      .replace(/[^a-z0-9]/gi, "-")
      .toLowerCase();
    doc.save(`FieldScribe-Report-${slug}.pdf`);
  };

  return (
    <div className="space-y-4">
      {/* Generate button row */}
      <div className="flex items-center justify-between">
        <div className="text-sm text-slate-400">
          {notes.length > 0 || imageAnalyses.length > 0 ? (
            <span>
              {imageAnalyses.length} photo{imageAnalyses.length !== 1 ? "s" : ""},{" "}
              {notes.length} note{notes.length !== 1 ? "s" : ""}
            </span>
          ) : (
            <span className="italic">Add photos or voice notes first</span>
          )}
        </div>
        <button
          onClick={handleGenerate}
          disabled={isGenerating || (!hasData && !hasDetails)}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm font-semibold hover:bg-indigo-700 disabled:opacity-40 disabled:cursor-not-allowed shadow-sm transition-all hover:shadow-md"
        >
          {isGenerating ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Wand2 className="w-4 h-4" />
          )}
          {isGenerating ? "Generating…" : report ? "Regenerate" : "Generate Report"}
        </button>
      </div>

      {/* Error */}
      {errorMsg && (
        <div className="flex items-start gap-2 p-3 bg-red-50 border border-red-100 rounded-lg text-sm text-red-700">
          <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
          <span>{errorMsg}</span>
        </div>
      )}

      {/* Report output */}
      {report ? (
        <div className="border border-slate-200 rounded-xl bg-white shadow-sm overflow-hidden">
          {/* Toolbar */}
          <div className="flex items-center justify-between px-4 py-2.5 border-b border-slate-100 bg-slate-50">
            <span className="text-xs font-medium text-slate-500 uppercase tracking-wide">
              Preview
            </span>
            <div className="flex gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 text-xs text-slate-500 hover:text-slate-800 px-2 py-1 rounded hover:bg-slate-100 transition-colors"
              >
                {copied ? (
                  <CheckCheck className="w-3.5 h-3.5 text-green-500" />
                ) : (
                  <Copy className="w-3.5 h-3.5" />
                )}
                {copied ? "Copied!" : "Copy"}
              </button>
              <button
                onClick={handleDownloadText}
                className="flex items-center gap-1.5 text-xs text-slate-500 hover:text-slate-800 px-2 py-1 rounded hover:bg-slate-100 transition-colors"
              >
                <FileType className="w-3.5 h-3.5" />
                TXT
              </button>
              <button
                onClick={handleDownloadPDF}
                className="flex items-center gap-1.5 text-xs bg-slate-900 text-white px-3 py-1 rounded hover:bg-slate-700 transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                PDF
              </button>
            </div>
          </div>

          {/* Content */}
          <div className="p-4 max-h-[600px] overflow-y-auto">
            <pre className="whitespace-pre-wrap font-mono text-xs text-slate-700 leading-relaxed">
              {report}
            </pre>
          </div>
        </div>
      ) : (
        <div className="border-2 border-dashed border-slate-100 rounded-xl p-12 text-center text-slate-400 bg-slate-50/50">
          <FileText className="h-10 w-10 mx-auto mb-3 opacity-20" />
          <p className="text-sm">
            Fill in details, upload photos, and add voice notes, then click{" "}
            <strong className="text-slate-500">Generate Report</strong>.
          </p>
        </div>
      )}
    </div>
  );
}
