import Link from "next/link";
import { FileText } from "lucide-react";

export const metadata = {
  title: "Terms of Service — FieldScribe",
  description: "The terms governing your use of FieldScribe.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-slate-800">
      {/* Nav */}
      <header className="border-b border-slate-100 py-5 px-6">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 font-bold text-slate-900">
            <div className="bg-indigo-600 p-1.5 rounded-lg">
              <FileText className="h-4 w-4 text-white" />
            </div>
            FieldScribe
          </Link>
          <Link href="/" className="text-sm text-slate-500 hover:text-slate-900 transition-colors">
            ← Back to home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-extrabold text-slate-900 mb-3">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-12">Last updated: February 19, 2026</p>

        <Section title="1. Agreement to Terms">
          <p>
            By accessing or using FieldScribe (&quot;Service&quot;), you agree to be bound by these Terms
            of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use FieldScribe.
            These Terms apply to all users of the Service.
          </p>
        </Section>

        <Section title="2. License">
          <p>
            Upon completing a one-time payment, FieldScribe grants you a <strong>personal,
            non-exclusive, non-transferable, perpetual license</strong> to use the Service for
            your own professional or personal inspection reporting purposes.
          </p>
          <p className="mt-3">You may <strong>not</strong>:</p>
          <ul className="list-disc pl-6 space-y-2 text-slate-600 mt-2">
            <li>Resell, sublicense, or transfer your access to another person.</li>
            <li>Share your access credentials or cookies with others.</li>
            <li>Use the Service to build a competing product or service.</li>
            <li>Reverse-engineer, decompile, or otherwise attempt to extract the source code.</li>
          </ul>
        </Section>

        <Section title="3. Access &amp; Authentication">
          <p>
            Access to the FieldScribe dashboard is verified via a browser cookie set after
            a confirmed Stripe payment. You are responsible for:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-slate-600 mt-3">
            <li>Keeping your device and browser secure.</li>
            <li>
              Not sharing access with others — your license covers a single user on your own
              devices.
            </li>
            <li>
              Contacting us at{" "}
              <a href="mailto:support@fieldscribe.app" className="text-indigo-600 hover:underline">
                support@fieldscribe.app
              </a>{" "}
              if your access is lost or compromised.
            </li>
          </ul>
        </Section>

        <Section title="4. Acceptable Use">
          <p>You agree to use FieldScribe only for lawful purposes. You must not:</p>
          <ul className="list-disc pl-6 space-y-2 text-slate-600 mt-3">
            <li>Upload illegal, harmful, or infringing content.</li>
            <li>Use the Service to process confidential information without proper authorization.</li>
            <li>Attempt to overload, hack, or disrupt the Service or its infrastructure.</li>
            <li>Use automated scripts or bots to interact with the Service in bulk.</li>
            <li>
              Circumvent usage limits or abuse the AI inference APIs in a way that creates
              undue cost for FieldScribe.
            </li>
          </ul>
        </Section>

        <Section title="5. AI-Generated Content Disclaimer">
          <p>
            FieldScribe uses third-party AI models (Llama Vision, Whisper, Mistral) to analyze
            photos, transcribe audio, and generate report text. <strong>AI-generated content is
            not guaranteed to be accurate, complete, or error-free.</strong>
          </p>
          <p className="mt-3">
            You are solely responsible for reviewing, editing, and verifying all AI-generated
            content before it is used in any professional, legal, or regulatory context.
            FieldScribe does not provide legal, engineering, or professional advice.
            Reports generated by the Service are tools to assist your work — not substitutes for
            professional judgment.
          </p>
        </Section>

        <Section title="6. Pricing &amp; Refund Policy">
          <p>
            FieldScribe is offered as a <strong>one-time lifetime payment of $149 USD</strong>.
            There are no recurring fees or subscriptions.
          </p>
          <p className="mt-3">
            <strong>30-Day Money-Back Guarantee:</strong> If you are not satisfied for any reason,
            email us at{" "}
            <a href="mailto:support@fieldscribe.app" className="text-indigo-600 hover:underline">
              support@fieldscribe.app
            </a>{" "}
            within 30 days of your purchase and we will issue a full refund, no questions asked.
            After 30 days, purchases are non-refundable.
          </p>
        </Section>

        <Section title="7. Fair Use">
          <p>
            Your lifetime license includes AI processing for up to approximately 500 photos and
            voice notes per month. This covers the vast majority of professional inspectors.
            If your usage significantly exceeds this threshold and creates material cost for
            FieldScribe, we will contact you before taking any action. We will work with you
            to find a fair solution.
          </p>
        </Section>

        <Section title="8. Intellectual Property">
          <p>
            All content, trademarks, logos, and software that make up FieldScribe are the
            exclusive property of FieldScribe and its licensors. Your inspection reports,
            photos, and voice recordings remain <strong>your property</strong>. We claim no
            ownership over content you create using the Service.
          </p>
        </Section>

        <Section title="9. Limitation of Liability">
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, FIELDSCRIBE SHALL NOT BE LIABLE FOR ANY
            INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS
            OF PROFITS, DATA, OR BUSINESS OPPORTUNITIES, ARISING OUT OF OR RELATED TO YOUR USE
            OF THE SERVICE, EVEN IF FIELDSCRIBE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
            DAMAGES.
          </p>
          <p className="mt-3">
            IN NO EVENT SHALL FIELDSCRIBE&apos;S TOTAL LIABILITY TO YOU EXCEED THE AMOUNT YOU
            PAID FOR THE SERVICE IN THE 12 MONTHS PRECEDING THE CLAIM.
          </p>
        </Section>

        <Section title="10. Indemnification">
          <p>
            You agree to indemnify and hold harmless FieldScribe, its officers, employees, and
            agents from any claims, damages, losses, or expenses (including attorneys&apos; fees)
            arising out of (a) your use of the Service, (b) your violation of these Terms, or
            (c) your violation of any third-party rights.
          </p>
        </Section>

        <Section title="11. Disclaimers">
          <p>
            THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY
            KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. FIELDSCRIBE DOES NOT WARRANT
            THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT DEFECTS WILL BE
            CORRECTED.
          </p>
        </Section>

        <Section title="12. Service Availability">
          <p>
            We strive to maintain high availability but do not guarantee uninterrupted access.
            We may modify, suspend, or discontinue any part of the Service at any time. If we
            discontinue the Service entirely, we will provide reasonable notice and a prorated
            refund where applicable.
          </p>
        </Section>

        <Section title="13. Governing Law">
          <p>
            These Terms are governed by the laws of the applicable jurisdiction without regard
            to conflict of law provisions. Any disputes shall be resolved through binding
            arbitration before a recognized arbitration body, except that either party may seek
            injunctive relief in a court of competent jurisdiction.
          </p>
        </Section>

        <Section title="14. Changes to Terms">
          <p>
            We reserve the right to modify these Terms at any time. We will update the
            &quot;Last updated&quot; date and, for material changes, notify users by email where possible.
            Continued use of the Service after changes constitutes acceptance of the new Terms.
          </p>
        </Section>

        <Section title="15. Contact">
          <p>
            Questions about these Terms? Contact us at{" "}
            <a href="mailto:legal@fieldscribe.app" className="text-indigo-600 hover:underline">
              legal@fieldscribe.app
            </a>
            .
          </p>
        </Section>
      </main>

      <footer className="border-t border-slate-100 py-8 text-center text-xs text-slate-400">
        <Link href="/privacy" className="hover:text-slate-600 mr-4">Privacy Policy</Link>
        <Link href="/" className="hover:text-slate-600">FieldScribe Home</Link>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-bold text-slate-900 mb-4 pb-2 border-b border-slate-100">{title}</h2>
      <div className="text-slate-600 leading-relaxed space-y-3">{children}</div>
    </section>
  );
}
